#!/bin/bash
set -e
version="1.4"

# Check arguments
if [[ $# == 0 ]]; then
    echo "$(basename $0): requires an argument"
    exit 1
fi

# Arguments
if [ "$*" == "--help" ] || [ "$*" == "-h" ]; then
echo "Usage: $(basename "$(test -L "$0" && readlink "$0" || echo "$0")") [FILE] [OPTION]
Downloads a file you define or if a latest screenshot or photo from your phone.

  -s, --screenshot      download latest screenshot
  -p, --photo           download latest photo
  -l, --ls              list provied path files [default is /storage/emulated/0/ or /sdcard/]

  -v, --version         show version number
  -h, --help            show this help"
exit 0
fi

if [ "$1" == "-v" ] || [ "$1" == "--version" ]; then
    echo -e "$(basename "$(test -L "$0" && readlink "$0" || echo "$0")") Version: $version"
    exit 0
fi

if [ "$1" == "-l" ] || [ "$1" == "-ls" ] || [ "$1" == "--ls" ]; then
    path="$2"
    [ -z "$path" ] && path="/storage/emulated/0/"
    adb -d shell ls $path
    exit 0
fi

if [ "$1" == "-s" ] || [ "$1" == "--screenshot" ]; then
    file=$(adb -d shell ls -t /storage/emulated/0/Pictures/Screenshots | head -1)
    adb -d pull /storage/emulated/0/Pictures/Screenshots/$file $HOME/Downloads/.
    printf "\e]8;;file:$HOME/Downloads/$file\e\\$file\e]8;;\e\\: have been pulled down to your \e]8;;file:$HOME/Downloads/\e\\downloads\e]8;;\e\\ folder."
    exit 0
fi

if [ "$1" == "-p" ] || [ "$1" == "--photo" ]; then
    file=$(adb -d shell ls -t /storage/emulated/0/DCIM/Camera | head -1)
    adb -d pull /storage/emulated/0/DCIM/Camera/$file $HOME/Downloads/.
    printf "\e]8;;file:$HOME/Downloads/$file\e\\$file\e]8;;\e\\: have been pulled down to your \e]8;;file:$HOME/Downloads/\e\\downloads\e]8;;\e\\ folder."
    exit 0
fi


adb -d pull $1 $HOME/Downloads/.
printf "\e]8;;file:$HOME/Downloads/$1\e\\$1\e]8;;\e\\: have been pulled down to your \e]8;;file:$HOME/Downloads/\e\\downloads\e]8;;\e\\ folder."
