#!/bin/bash
set -e
scriptName=$(basename "$(test -L "$0" && readlink "$0" || echo "$0")")

# Help
fn_help () {
  echo "Usage: $scriptName [FILE] [OPTION]"
  echo "Files are uploaded to the download directory."
  echo ""
  echo "  -s SERIAL             use device with given serial"
  echo ""
  echo "  --devices             list connected devices"
  echo ""
  echo "  -h, --help            show this help"
  exit 0
}

# Local functions
_fn_upload_success_message () {
    file=$(basename $1)
    echo "$file: file have been pushed to ./storage/emulated/0/Download/$file"
}

# Main functions
fn_default () {
    if [[ "$1" != "false" ]]; then
        adb -s $1 -d push "$2" "/storage/emulated/0/Download/$2"
    else
        adb -d push "$2" "/storage/emulated/0/Download/$2"
    fi
    _fn_upload_success_message $2
    exit 0
}

fn_devices () {
    adb devices -l
    exit 0
}

# Main
main () {
    if [[ $# == 0 ]]; then
        echo "$scriptName: requires an argument"
        exit 1
    fi

    if [[ "$*" == *"-h"* ]] || [[ "$*" == *"--help"* ]]; then fn_help; fi

    device=false
    [[ "$1" == "-s" ]] && device=$2
    [[ -z $device ]] && echo "$scriptName: -s requires an argument" && exit 1

    if [[ "$device" == "false" ]]; then
        if [[ "$1" == "--devices" ]]; then fn_devices; fi
        fn_default $device $1
    else
        if [[ "$3" == "--devices" ]]; then fn_devices; fi
        fn_default $device $3
    fi
}

main $*