#!/bin/bash
set -e
version="1.1"

# Check arguments
if [[ $# == 0 ]]; then
    echo "$(basename $0): requires an argument"
    exit 1
fi

# Arguments
if [ "$*" == "--help" ] || [ "$*" == "-h" ]; then
echo "Usage: $(basename "$(test -L "$0" && readlink "$0" || echo "$0")") [FILE] [OPTION]
Files are automaticly uploaded to the download directory.

  -v, --version         show version number
  -h, --help            show this help"
exit 0
fi

if [ "$1" == "-v" ] || [ "$1" == "--version" ]; then
    echo -e "$(basename "$(test -L "$0" && readlink "$0" || echo "$0")") Version: $version"
    exit 0
fi



adb push $1 /sdcard/Download/$2
echo $1: have been pushed to ./sdcard/Download/$2
