#!/bin/bash
set -e
version="1.2"

# Check arguments
if [[ $# == 0 ]]; then
    echo "$(basename $0): requires an argument"
    exit 1
fi

# Arguments
if [ "$*" == "--help" ] || [ "$*" == "-h" ]; then
echo "Usage: $(basename "$(test -L "$0" && readlink "$0" || echo "$0")") [FILE] [OPTION]
Downloads a file you define or if a latest screenshot or photo from your phone.

  -s, --screenshot      download latest screenshot
  -p, --photo           download latest photo
  -l, --ls              list provied path files [/sdcard to find your files]

  -v, --version         show version number
  -h, --help            show this help"
exit 0
fi

if [ "$1" == "-v" ] || [ "$1" == "--version" ]; then
    echo -e "$(basename "$(test -L "$0" && readlink "$0" || echo "$0")") Version: $version"
    exit 0
fi

if [ "$1" == "-l" ] || [ "$1" == "--ls" ]; then
    adb -d shell ls $2
    exit 0
fi

if [ "$1" == "-s" ] || [ "$1" == "--screenshot" ]; then
    file=$(adb shell ls -t /sdcard/Pictures/Screenshots | head -1)
    adb -d pull /sdcard/Pictures/Screenshots/$file $HOME/Downloads/.
    echo $file: have been pulled down to your download folder.
    exit 0
fi

if [ "$1" == "-p" ] || [ "$1" == "--photo" ]; then
    file=$(adb shell ls -t /sdcard/DCIM/Camera | head -1)
    adb -d pull /sdcard/DCIM/Camera/$file $HOME/Downloads/.
    echo $file: have been pulled down to your download folder.
    exit 0
fi


adb -d pull $1 $HOME/Downloads/.
echo $1: have been pulled down to your download folder.
