#!/bin/bash

if [[ -z "$1" ]]; then
    # No argument: use today's date in milliseconds
    echo "$(date +%s)000"
else
    # Argument provided: convert given date string to milliseconds
    echo "$(date -d "$1" +%s)000"
fi