#!/bin/bash
# Needs to me first in path

emulator_proxy_function () {
    if [ ! -f $ANDROID_HOME/emulator/emulator-x86 ]; then
        ln $ANDROID_HOME/emulator/emulator $ANDROID_HOME/emulator/emulator-x86
    fi
    
    # setup config dir
    if [ ! -d ~/.config/emulator_proxy/ ]; then mkdir ~/.config/emulator_proxy; fi

    # Read config
    if [ -f ~/.config/emulator_proxy/default ]; then
        defaultEmulator=$(cat ~/.config/emulator_proxy/default)
    else
        defaultEmulator=""
    fi

    if [ "$1" == "-l" ] || [ "$1" == "--list" ] || [ "$1" == "-list-avds" ]; then
        echo "AVD devices:"
        for e in $(emulator-x86 -list-avds); do
            if [ $e == $defaultEmulator ]; then
                echo "  $e (Default)"
            else
                echo "  $e"
            fi
        done
        exit 0
    fi
    if [ "$1" == "-d" ] || [ "$1" == "--default" ]; then
        if [ "$defaultEmulator" == "" ]; then echo "No default emulator defined"; exit 1; fi
        emulator-x86 -avd $defaultEmulator >/dev/null 2>&1 &
        exit 0
    fi
    if [ "$1" == "--set" ]; then
        if [ "$2" == "" ]; then echo "No default emulator defined"; exit 1; fi
        avalibleEmulators="$(emulator -list-avds)"
        if ! echo ${avalibleEmulators[@]} | grep -q -w "$2"; then echo "'$2' is not a valid emulator"; exit 1; fi
        echo "$2" > ~/.config/emulator_proxy/default
        echo "Default emulator set to '$2'"
        exit 0
    fi
    if [ "$1" == "--kill" ]; then
        killall -s SIGKILL qemu-system-x86_64 2>/dev/null
        exit 0
    fi
    if [ "$1" == "--clear" ]; then
        if [ "$defaultEmulator" == "" ]; then echo "No default emulator defined"; exit 1; fi
        killall -s SIGKILL qemu-system-x86_64 2>/dev/null
        sleep 4
        rm $ANDROID_AVD_HOME/$defaultEmulator.avd/*.lock 2>/dev/null
        exit 0
    fi
    
    if [[ $# -eq 0 ]]; then
        emulator-x86 $*
        echo "AVD devices:"
        for e in $(emulator -list-avds); do
            if [ $e == $defaultEmulator ]; then
                echo "  $e (Default)"
            else
                echo "  $e"
            fi
        done
        echo "
Extended commands:
  -d, --default           Open the set default emulator
  -l, --list              List avalible AVDs (alias to list-avds)
  --set                   Set the defualt emulator
  --kill                  Kill all emulators
  --clear                 Kill and clear default emulator and lockfile
"
        exit 1
    fi
    emulator-x86 $*
}
emulator_proxy_function $*