#!/bin/bash
#
# This script Require GIT and GH to function propperly
# Best usage is to add the script to your git aliases
# > [alias]
# >	checkout-pr = "!bash git-checkout-pr"

if [ $# -eq 0 ]; then
    echo -e "No pull request number provided"
    gh pr list
    echo -e "\nNote: that you cant use # in the name"
    exit 1
fi

if [ $(gh pr list | grep -wc "$*") == 0 ]; then
    echo -e "Can not find pull request #$*"
    gh pr list
    exit 1
fi

branch=$(gh pr list | grep "$*" | cut -f3 | sed 's/.*://')
git checkout "${branch}"

if [ $? -eq 1 ]; then
    echo "Obtaining remote and checking out branch."
    gh pr checkout $1
fi
