#!/bin/bash
# .config/i3status/config
#       read_file phone {
#               path = "/home/andre/.cache/i3status_monitor/phone"
#               format = "%content"
#               format_bad = ""
#       }

_device="device:OnePlusNordCE"
_symbol="✆"

_file="phone"
_path="$HOME/.cache/i3status_monitor"

while true; do 
    sleep 10

    [ ! -d "$_path" ] && mkdir -p $_path

    if [[ $(pgrep adb) ]]; then
        if [[ $(adb devices -l | grep "$_device") ]]; then
            echo "Android device connected"
            echo "$_symbol"  > $_path/$_file
            continue
        fi
    else
        echo "Warning: adb server not running"
        echo "" > $_path/$_file
        continue
    fi

    echo "No device connected"
    echo "" > $_path/$_file
done
