#!/bin/bash
# .config/i3status/config
#       read_file dotfiles {
#               path = "/home/andre/.cache/i3status_monitor/dotfiles"
#               format = "%content"
#               format_bad = ""
#               color_good = "#DC322F"
#               color_bad = "#DC322F"
#       }

_device="device:OnePlusNordCE"
_symbol="✆"

_file="dotfiles"
_path="~/.cache/i3status_monitor"

while true; do 
    sleep 10

    [ ! -d "$_path" ] && mkdir -p "$_path"

    if [[ ! $(git -C ~/Repositories/dotfiles status | grep nothin) || $(git -C ~/Repositories/dotfiles status | grep Untracked) ]]; then
        echo "Changes detected (dotfiles)"
        echo "!"  > $_path/$_file
        continue
    fi
    if [[ ! $(git -C ~/Repositories/dotfiles_private status | grep nothin) || $(git -C ~/Repositories/dotfiles_private status | grep Untracked) ]]; then
        echo "Changes detected (dotfiles_private)"
        echo "!"  > $_path/$_file
        continue
    fi
    if [[ ! $(git -C ~/Repositories/Tools status | grep nothin) || $(git -C ~/Repositories/Tools status | grep Untracked) ]]; then
        echo "Changes detected (Tools)"
        echo "!"  > $_path/$_file
        continue
    fi
    echo "No Changed detected"
    echo "" > $_path/$_file
done
