#!/bin/bash

scriptName=$(basename "$(test -L "$0" && readlink "$0" || echo "$0")")
isNumber='^[0-9]+$'

fn_help () {
    echo "Usage: $scriptName [OPTION]"
    echo ""
    echo "Prints or writes a random generated text from metaphorpsum."
    echo "Each option have 2 optional parameter of a number. For a set amount of sentences define one number:"
    echo "   Exsample: $scriptName -p 1"
    echo "To get a random number between 1 och 3 you define a secondary parameter"
    echo "   Exsample: $scriptName -p 1 3"
    echo ""
    echo "  -p, --print           print a random lorem ipsum text"
    echo "  -w, --write           write a random lorem ipsum text to your cursor location"
    echo ""
    echo "  -h, --help            show this help"

    exit 0
}
fn_error () {
    echo "$scriptName: $*"
    exit 1 
}

fn_print () {
    if [[ ! -z $1 ]] && [[ $1 =~ $isNumber ]]; then _RANDS=$1; else _RANDS=1; fi
    if [[ ! -z $2 ]] && [[ $2 =~ $isNumber ]]; then _RANDE=$2; else _RANDE=1; fi

    RAND=$(($_RANDS + $RANDOM % $_RANDE))
    LOREM="$(curl -s http://metaphorpsum.com/sentences/$RAND)"
    echo "$LOREM"
    exit 0
}

fn_write () {
    if [[ -z $1 ]] && [[ $1 =~ $isNumber ]]; then _RANDS=$1; else _RANDS=1; fi
    if [[ -z $2 ]] && [[ $2 =~ $isNumber ]]; then _RANDE=$2; else _RANDE=1; fi
    if [[ ! -z $1 ]] && [[ ! -z $2 ]] ; then _RANDS=1; _RANDE=1; fi

    sleep 0.5
    RAND=$(($_RANDS + $RANDOM % $_RANDE))
    LOREM="$(curl -s http://metaphorpsum.com/sentences/$RAND)"
    xdotool type "$LOREM"
    exit 0
}

main () {
    if [[ $# -gt 3 ]]; then fn_error "To many arguments"; fi

    if [[ "$*"  == "--help" ]] || [[ "$1"  == "-h" ]]; then fn_help; fi
    if [[ "$1"  == "--write" ]] || [[ "$1"  == "-w" ]]; then fn_write $2 $3; fi
    if [[ "$1"  == "--print" ]] || [[ "$1"  == "-p" ]]; then fn_print $2 $3; fi
    
    if [[ $# == 0 ]]; then fn_print; fi
    
    fn_error "'$*' invalid argument"
}

main $*
