#!/bin/bash

NAME=$(basename "$(test -L "$0" && readlink "$0" || echo "$0")")
LOREM="$(curl -s http://metaphorpsum.com/sentences/${1-3})"

main () {
    if [ "$*" == "--help" ] || [ "$*" == "-h" ]; then
        echo "Usage: $NAME [OPTION]
  print a random length of Lorem Ipsum text\n  
  -w, --write           write a random lorem ipsum text to your cursor location
  
  -h, --help            show this help"
    exit 0
    fi

    if [ "$*" == "--write" ] || [ "$*" == "-w" ]; then
        sleep 0.5
        xdotool type "$LOREM"
        exit 0
    fi
    echo "$LOREM"
    exit 0
}

main $*
