#!/bin/bash

NAME=$(basename "$(test -L "$0" && readlink "$0" || echo "$0")")
LOREM="$(lorem-ipsum-generator -s $(($RANDOM%10+1)))"

android () {
    if [[ $(adb devices -l | grep "device usb:") ]]; then 
        echo "Sending text to devices/emulators:\n$LOREM"
        LOREM=`echo $LOREM | sed "s/\s/\%s/g"`
        LOREM=`echo $LOREM | sed "s/\n/\%n/g"`
        adb shell input text "$LOREM"
        exit 0
    fi
    echo "$NAME error: No devices/emulators found"
    exit 1
}

main () {
    if [ "$*" == "--help" ] || [ "$*" == "-h" ]; then
        echo "Usage: $NAME [OPTION]
  print a random length of Lorem Ipsum text\n  
  -a, --android         sends a random lorem ipsum text to device/emulator
  -w, --write           write a random lorem ipsum text to your cursor location
  
  -h, --help            show this help"
    exit 0
    fi

    if [ "$*" == "--android" ] || [ "$*" == "-a" ]; then
        android
        exit 0
    fi
    if [ "$*" == "--write" ] || [ "$*" == "-w" ]; then
        sleep 0.5
        xdotool type "$LOREM"
        exit 0
    fi
    echo "$LOREM"
}

main $*
