#!/bin/bash
# .config/i3status/config
#    read_file dotfiles {
#            path = "/home/andre/.cache/dotfileWatcher/log"
#            format = "%content"
#            format_bad = ""
#            color_good = "#DC322F"
#            color_bad = "#DC322F"
#    }

while true; do 
    sleep 10

    [ ! -d "$HOME/.cache/dotfileWatcher" ] && mkdir -p "$HOME/.cache/dotfileWatcher"

    if [[ ! $(git -C ~/Repositories/dotfiles status | grep nothin) || $(git -C ~/Repositories/dotfiles status | grep Untracked) ]]; then
        echo "Changes detected (dotfiles)"
        echo "!"  > $HOME/.cache/dotfileWatcher/log
        continue
    fi
    if [[ ! $(git -C ~/Repositories/dotfiles_private status | grep nothin) || $(git -C ~/Repositories/dotfiles_private status | grep Untracked) ]]; then
        echo "Changes detected (dotfiles_private)"
        echo "!"  > $HOME/.cache/dotfileWatcher/log
        continue
    fi
    echo "No Changed detected"
    echo "" > $HOME/.cache/dotfileWatcher/log
done
