#!/bin/bash
# .config/i3status/config
#        read_file android {
#                path = "/home/andre/.cache/androidDeviceWatcher/log"
#                format = "%content"
#                format_bad = ""
#        }

while true; do 
    sleep 10

    [ ! -d "$HOME/.cache/androidDeviceWatcher" ] && mkdir -p "$HOME/.cache/androidDeviceWatcher"

    if [[ $(pgrep adb) ]]; then
        if [[ $(adb devices -l | grep "device usb:") ]]; then
            echo "Android device connected"
            echo "✆"  > $HOME/.cache/androidDeviceWatcher/log
            continue
        fi
    else
        echo "Warning: adb server not running"
        echo "" > $HOME/.cache/androidDeviceWatcher/log
        continue
    fi

    echo "No device connected"
    echo "" > $HOME/.cache/androidDeviceWatcher/log
done
