#!/bin/bash
version="2.00"

if [ "$*" == "--help" ] || [ "$*" == "-h" ]; then
echo "Usage: $(basename "$(test -L "$0" && readlink "$0" || echo "$0")") VERSION|options

  -l   --list            show a list of avalible versions
  -v,  --version         show version number
  -h,  --help            show this help"
exit 0
fi

if [ "$*" == "-v" ] || [ "$*" == "--version" ]; then
    node -v
    exit 0
fi

if [ "$*" == "-l" ] || [ "$*" == "--list" ]; then
    #echo " > node 10"
    #echo " > node 12"
    echo " > node 14"
    echo " > node 16"
    echo " > node 18"
    echo " > node 20"
    echo " > node latest"
    echo

    if [ -x "$(command -v node)" ]; then
        printf "Current version: "
        node -v
    fi
    exit 0
fi

if [ "$1" == '' ]; then
    echo -e "Usage: $(basename "$(test -L "$0" && readlink "$0" || echo "$0")") VERSION|options"
    echo "No version provided"
    echo

    if [ -x "$(command -v node)" ]; then
        printf "Current version: "
        node -v
    fi
    exit 1
fi

if [ "$1" == "10" ]; then
    echo "nodejs version 10* (nodejs-lts-dubnium) is no longer supported"
    exit 1
elif [ "$1" == "12" ]; then
    echo "nodejs version 12* (nodejs-lts-erbium) is no longer supported"
    exit 1
elif [ "$1" == "14" ]; then
    PACKAGE_NAME=nodejs-lts-fermium
elif [ "$1" == "16" ]; then
    PACKAGE_NAME=nodejs-lts-gallium
elif [ "$1" == "18" ]; then
    PACKAGE_NAME=nodejs-lts-hydrogen
elif [ "$1" == "20" ]; then
    PACKAGE_NAME=nodejs-lts-iron
elif [ "$1" == "latest" ]; then
    PACKAGE_NAME=nodejs
else
    echo "No version '$1' was found are you sure you spelled it right?"; exit 1
fi

yes "" | sudo pacman -Sy "$PACKAGE_NAME"
echo -e "\nVersion have been changed to $(node -v)"
exit 0