#!/bin/bash
echo -e """
Normal \e[8mHidden\e[0m            \e[39mDefault\e[0m               \e[49mDefault\e[0m
Normal \e[7minverted\e[0m          \e[30mBlack\e[0m                 \e[40mBlack\e[0m
Normal \e[5mBlink\e[0m             \e[90mDark gray\e[0m             \e[100mDark gray\e[0m
Normal \e[4mUnderlined\e[0m        \e[37mLight gray\e[0m            \e[47mLight gray\e[0m
Normal \e[2mDim\e[0m               \e[36mCyan\e[0m                  \e[46mCyan\e[0m
Normal \e[1mBold\e[0m              \e[96mLight cyan\e[0m            \e[106mLight cyan\e[0m
                         \e[35mMagenta\e[0m               \e[45mMagenta\e[0m
                         \e[95mLight magenta\e[0m         \e[105mLight magenta\e[0m
                         \e[34mBlue\e[0m                  \e[44mBlue\e[0m
                         \e[94mLight blue\e[0m            \e[104mLight blue\e[0m
                         \e[33mYellow\e[0m                \e[43mYellow\e[0m
                         \e[93mLight yellow\e[0m          \e[103mLight yellow\e[0m
                         \e[32mGreen\e[0m                 \e[42mGreen\e[0m
                         \e[92mLight green\e[0m           \e[102mLight green\e[0m
                         \e[31mRed\e[0m                   \e[41mRed\e[0m
                         \e[91mLight red\e[0m             \e[101mLight red\e[0m
                         \e[97mWhite\e[0m                 \e[107mWhite\e[0m
"""

echo ""

# This program is free software. It comes without any warranty, to
# the extent permitted by applicable law. You can redistribute it
# and/or modify it under the terms of the Do What The Fuck You Want
# To Public License, Version 2, as published by Sam Hocevar. See
# http://sam.zoy.org/wtfpl/COPYING for more details.
#Background
for clbg in {40..47} {100..107} 49 ; do
	#Foreground
	for clfg in {30..37} {90..97} 39 ; do
		#Formatting
		for attr in 0 1 2 4 5 7 ; do
			#Print the result
			echo -en "\e[${attr};${clbg};${clfg}m ^[${attr};${clbg};${clfg}m \e[0m"
		done
		echo #Newline
	done
done

# This program is free software. It comes without any warranty, to
# the extent permitted by applicable law. You can redistribute it
# and/or modify it under the terms of the Do What The Fuck You Want
# To Public License, Version 2, as published by Sam Hocevar. See
# http://sam.zoy.org/wtfpl/COPYING for more details.
for fgbg in 38 48 ; do # Foreground / Background
    for color in {0..255} ; do # Colors
        # Display the color
        printf "\e[${fgbg};5;%sm  %3s  \e[0m" $color $color
        # Display 6 colors per lines
        if [ $((($color + 1) % 6)) == 4 ] ; then
            echo # New line
        fi
    done
    echo # New line
done

exit 0