#!/bin/bash

_mainPwd="$PWD"
_repoDir="$HOME/Repositories"

_status=()

_arg_update="false"
[[ ! -z "$1" ]] && [[ "$1" == "update" ]]    && _arg_update="true"
[[ ! -z "$1" ]] && [[ "$1" == "upgrade" ]]   && _arg_update="true"
[[ ! -z "$1" ]] && [[ "$1" == "u" ]]         && _arg_update="true"
[[ ! -z "$1" ]] && [[ "$1" == "U" ]]         && _arg_update="true"
[[ ! -z "$1" ]] && [[ "$1" == "-u" ]]        && _arg_update="true"
[[ ! -z "$1" ]] && [[ "$1" == "-U" ]]        && _arg_update="true"

echo -e "\e[2mChecking dotfile repo status\e[0m"
if [[ "$_arg_update" == "true" ]]; then
    echo -e "\e[2mUpdating repos if no changes are found\e[0m"
fi

if [[ ! -d "$_repoDir" ]]; then
    echo "Repositories directory not found..."
    exit 1
fi

# Collect issues
cd $_repoDir
_dotfiles=("$_repoDir/dotfiles" "$_repoDir/dotfiles_private" "$_repoDir/wdotfiles" "$_repoDir/secure" "$_repoDir/Tools")
for _path in "${_dotfiles[@]}"; do
    [[ ! -d "$_path" ]] && continue
    if [[ ! $(git -C $_path status | grep nothin) || $(git -C $_path status | grep Untracked) ]]; then
        _status+=("\e]8;;$_path\a$(basename $_path)\e]8;;\a\e[0m: uncommitted changes")
        continue
    fi
    if [[ "$_arg_update" == "true" ]]; then
        cd $_path
        _gitPull="$(git pull)"
        cd $_repoDir
        [[ $(echo $_gitPull | grep Already) ]] && continue
        _status+=("\e]8;;$_path\a$(basename $_path)\e]8;;\a\e[0m: $_gitPull")
    fi
done

# Print sitrep
if [ ${#_status[@]} -gt 0 ]; then
    echo -e "\nCurrent status:"
    for _sitrep in "${_status[@]}"; do
        echo -e " - $_sitrep"
    done
else
    echo "All good"
fi

cd $_mainPwd
