#!/bin/bash

if [[ -z "$1" ]]; then
    # No argument: show today's date
    date "+%Y-%m-%d %H:%M:%S"
else
    # Argument: convert Unix timestamp to date
    timestamp="$1"
    
    # Check if timestamp is in milliseconds (13+ digits) or seconds (10 digits or less)
    if [[ ${#timestamp} -gt 10 ]]; then
        # Milliseconds timestamp - convert to seconds
        seconds="${timestamp:0:-3}"
        milliseconds="${timestamp: -3}"
        date -d "@$seconds" "+%Y-%m-%d %H:%M:%S.${milliseconds}"
    else
        # Regular seconds timestamp
        date -d "@$timestamp" "+%Y-%m-%d %H:%M:%S"
    fi
fi