#!/bin/bash
set -e

if [ $# -eq 0 ]; then
  exit 1
fi

if ! command -v $1 >/dev/null 2>&1; then
  echo "what: $1 not found"
  exit 1
fi

type $1
ls -l $(which $1) | awk {'print "main: "$9" "$10" "$11'}
which -a $1