#!/bin/bash

SCRIPT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )"

echo -e "\033[34;1mCopying scripts\033[0m"
cd $SCRIPT_DIR/ScriptsLinux
[ ! -d "$HOME/.bin" ] && mkdir -p $HOME/.bin
EXISTING=($(ls /usr/bin/))
for FILE in $(rg --files --hidden); do
    if [[ " ${EXISTING[*]} " =~ " ${FILE} " ]]; then
        echo -e " \033[2mScript '$FILE' already pressent in /usr/bin skipping\033[0m"
        continue
    fi
    if [[ $* == ln ]]; then 
        echo -e " \033[2mLinking $FILE => ./ScriptsLinux/$FILE\033[0m"
        rm -f $HOME/.bin/$FILE
        ln -sf $SCRIPT_DIR/ScriptsLinux/$FILE $HOME/.bin/$FILE
    else
        echo -e " \033[2mCopying $FILE\033[0m"
        rm -f $HOME/.bin/$FILE
        cp $SCRIPT_DIR/ScriptsLinux/$FILE $HOME/.bin/$FILE
    fi
done