#!/bin/bash
version="1.00"

if [ "$*" == "--help" ] || [ "$*" == "-h" ]; then
echo "Usage: $(basename "$(test -L "$0" && readlink "$0" || echo "$0")") VERSION|options

-l   --list            show a list of avalible versions
-v,  --version         show version number

-h,  --help            show this help"
exit 0
fi

if [ "$*" == "-v" ] || [ "$*" == "--version" ]; then
    echo -e "$(basename "$(test -L "$0" && readlink "$0" || echo "$0")") Version: $version\n"
    exit 0
fi

if [ "$*" == "-l" ] || [ "$*" == "--list" ]; then
    for entry in /usr/local/lib/nodejs/* ; do
        ver=$(echo $(basename $entry) | sed "s/.*node\-\(.*\)\-linux.*/\1/g")
        if [ "$ver" == "current" ]; then
            echo "Current $($entry/bin/node -v)"
        else
            echo "  > node $ver"
        fi 
    done
    exit 0
fi

if [ "$1" == '' ]; then echo -e "Usage: $(basename "$(test -L "$0" && readlink "$0" || echo "$0")") VERSION|options\nNo version provided"; exit 1; fi

for entry in /usr/local/lib/nodejs/* ; do
    ver=$(echo $(basename $entry) | sed "s/.*node\-\(.*\)\-linux.*/\1/g")
    if [ "$1" == "$ver" ]; then 
        if [ "$1" == "$(/usr/local/bin/node -v)" ]; then echo "You are alrerady on version $1"; exit 0; fi
        sudo rm /usr/local/bin/node
        sudo rm /usr/local/bin/nodejs
        sudo rm /usr/local/lib/nodejs/current

        sudo ln -s $entry /usr/local/lib/nodejs/current
        sudo ln /usr/local/lib/nodejs/current/bin/node /usr/local/bin/node
        sudo ln /usr/local/lib/nodejs/current/bin/node /usr/local/bin/nodejs
        
        echo "Node version have been changed to $1"
        exit 0
    fi
done
echo "No version '$1' was found are you sure you spelled it right?"
exit 1