#!/bin/sh
exec tail -n +3 $0

# How to set it up
#  Windows
#   Make sure UUID (ex: 6414-FC76) is set to the boot parition (ex: dev/sdd1).
#  Linux
#   Make sure disks and gpt match (ex: /dev/sdb3 gpt3)
#   Make sure UUID is correct to drive
#   Make sure linux (/boot/vmlinuz) and initrd (/boot/initrd.img) is defined on the dist
#

menuentry 'Windows 10                   (on /dev/sdd)' --class windows --class os {
	savedefault
	search --fs-uuid --no-floppy --set=root 6414-FC76
	chainloader (${root})/EFI/Microsoft/Boot/bootmgfw.efi
}

menuentry 'Linux Mint (20)              (on /dev/sdb3)' --class gnu-linux --class gnu --class os $menuentry_id_option 'osprober-gnulinux-/boot/vmlinuz--b86cc7b7-cad8-4c78-9e63-a6fd1d39a3ac' {
	savedefault
	insmod part_gpt
	insmod ext2
	set root='hd1,gpt3'
	if [ x$feature_platform_search_hint = xy ]; then
		search --no-floppy --fs-uuid --set=root --hint-ieee1275='ieee1275//disk@0,gpt3' --hint-bios=hd1,gpt3 --hint-efi=hd1,gpt3 --hint-baremetal=ahci1,gpt3  b86cc7b7-cad8-4c78-9e63-a6fd1d39a3ac
	else
		search --no-floppy --fs-uuid --set=root b86cc7b7-cad8-4c78-9e63-a6fd1d39a3ac
	fi
	linux /boot/vmlinuz root=/dev/sdb3
	initrd /boot/initrd.img
} 
menuentry 'Manjaro (20.2)               (on /dev/sdb4)' --class gnu-linux --class gnu --class os $menuentry_id_option 'osprober-gnulinux-/boot/vmlinuz-5.10-x86_64--c950df16-d736-4a1b-a917-a4bb9a5ea2f7' {
	savedefault
	insmod part_gpt
	insmod ext2
	set root='hd1,gpt4'
	if [ x$feature_platform_search_hint = xy ]; then
		search --no-floppy --fs-uuid --set=root --hint-ieee1275='ieee1275//disk@0,gpt4' --hint-bios=hd1,gpt4 --hint-efi=hd1,gpt4 --hint-baremetal=ahci1,gpt4  c950df16-d736-4a1b-a917-a4bb9a5ea2f7
	else
		search --no-floppy --fs-uuid --set=root c950df16-d736-4a1b-a917-a4bb9a5ea2f7
	fi
	linux /boot/vmlinuz-5.10-x86_64 root=/dev/sdb4
	initrd /boot/initramfs-5.10-x86_64.img
}
menuentry 'PLAYipp                      (on /dev/sdb6)' --class gnu-linux --class gnu --class os $menuentry_id_option 'osprober-gnulinux-/boot/vmlinuz-5.4-x86_64--e87fa6b9-5b0d-4b82-be11-19f5c5abbda6' {
	savedefault
	insmod part_gpt
	insmod ext2
	set root='hd1,gpt6'
	if [ x$feature_platform_search_hint = xy ]; then
		search --no-floppy --fs-uuid --set=root --hint-ieee1275='ieee1275//disk@0,gpt6' --hint-bios=hd1,gpt6 --hint-efi=hd1,gpt6 --hint-baremetal=ahci1,gpt6  e87fa6b9-5b0d-4b82-be11-19f5c5abbda6
	else
		search --no-floppy --fs-uuid --set=root e87fa6b9-5b0d-4b82-be11-19f5c5abbda6
	fi
	linux /boot/vmlinuz-5.10-x86_64 root=/dev/sdb6
	initrd /boot/initramfs-5.10-x86_64.img
}
